local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

ls.add_snippets("cpp", {
  s("cp", {
    t({
      "#include <bits/stdc++.h>",
      "",
      "using namespace std;",
      "",
      "template<typename A, typename B>",
      "ostream& operator<<(ostream &os, const pair<A, B> &p) {",
      "    return os << '(' << p.first << \", \" << p.second << ')';",
      "}",
      "",
      "template<typename T_container, typename T = typename enable_if<!is_same<T_container, string>::value, typename T_container::value_type>::type>",
      "ostream& operator<<(ostream &os, const T_container &v) {",
      "    os << '{';",
      "    string sep;",
      '    for (const T &x : v) os << sep << x, sep = ", ";',
      "    return os << '}';",
      "}",
      "",
      "void dbg_out() { cerr << endl; }",
      "template<typename Head, typename... Tail>",
      "void dbg_out(Head H, Tail... T) {",
      "    cerr << ' ' << H;",
      "    dbg_out(T...);",
      "}",
      "",
      "#ifdef LOCAL",
      '#define dbg(...) cerr << "(" << #__VA_ARGS__ << "):", dbg_out(__VA_ARGS__)',
      "#else",
      "#define dbg(...)",
      "#endif",
      "",
      "#define zab __builtin_clz",
      "#define zae __builtin_ctz",
      "#define oness __builtin_popcount",
      "#define pb push_back",
      "#define fi first",
      "#define se second",
      "#define ar array",
      "#define ll long long",
      "#define ld long double",
      "#define sza(x) ((int)x.size())",
      "#define all(a) (a).begin(), (a).end()",
      "#define rall(x) (x).rbegin, (x).rend()",
      "#define rep(i,n) for(int i = 0; i < (n); i++)",

      "typedef vector<int> vi;",
      "typedef vector<vi> vvi;",
      "typedef pair<int, int> ii;",
      "typedef vector<ii> vii;",
      "typedef vector<ll> vll;",
      "typedef vector<vll> vvll;",
      "",
      "const int MAX_N = 1e5 + 5;",
      "const ll MOD = 1e9 + 7;",
      "const ll INF = 1e9;",
      "const ld EPS = 1e-9;",
      "",
      "",
      "void solve() {",
      "    ",
    }),
    i(1, ""),
    t({
      "",
      "}",
      "",
      "int main() {",
      "    ios_base::sync_with_stdio(0);",
      "    cin.tie(0); cout.tie(0);",
      "    int i; //don't pick i as a variable :<",
      "    int tc;",
      "    cin >> tc;",
      "    for (int t = 0; t < tc; t++) {",
      '        // cout << "Case #" << t << ": ";',
      "        solve();",
      "    }",
      "}",
    }),
  }),
})
